# Use a lightweight Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the remaining app files
COPY . .

# Expose port 3000 (or the port your Express app is listening on)
EXPOSE 5001

# Start the Node.js app
CMD ["npm", "start"]
