name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username homeshw --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f Dockerfile.production . --tag ghcr.io/homeshw/speech_therapy_server:latest
          docker push ghcr.io/homeshw/speech_therapy_server:latest
